#  PORT
quarkus.http.port=8620
quarkus.http.host=localhost
quarkus.http.root-path=kick

#  CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,X-Requested-With

#  DataSource (PostgreSQL - Supabase)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
quarkus.datasource.username=postgres.yttvginrhrqmbchiykaz
quarkus.datasource.password=${SUPABASE_PASSWORD}
quarkus.datasource.devservices.enabled=false

#  JPA/Hibernate ORM
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.log.sql=true

#  Logs
quarkus.log.level=INFO
quarkus.log.console.enabled=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.file.enabled=true
quarkus.log.file.path=logs/gestudiantes.log
quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.file.rotation.max-file-size=5M
quarkus.log.file.rotation.max-backup-index=5
quarkus.log.file.rotation.file-suffix=yyyy-MM-dd

#  OpenAPI / Swagger UI
quarkus.swagger-ui.enabled=true
#quarkus.swagger-ui.always-include=true
#quarkus.swagger-ui.path=/swagger-ui

quarkus.smallrye-openapi.info-title=Gestion de docentes demo - Vinni
quarkus.smallrye-openapi.info-version=V1
quarkus.smallrye-openapi.info-description=API generado en Quarkus para gestion de Docentes
quarkus.smallrye-openapi.info-contact-name=vinni9@gmail.com

